CREATE TABLE workspace(
			id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
			wid INT(11) NOT NULL DEFAULT 0,
			name VARCHAR(11) NOT NULL DEFAULT '',
  		description VARCHAR(50) NOT NULL DEFAULT '',
  		PRIMARY KEY  (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE project(
			id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
			wid INT(11) NOT NULL DEFAULT 0,
			pid INT(11) NOT NULL DEFAULT 0,
			name VARCHAR(11) NOT NULL DEFAULT '',
  		description VARCHAR(100) NOT NULL DEFAULT '',
  		datasource VARCHAR(40) NOT NULL DEFAULT '',
  		schedule VARCHAR(30) NOT NULL DEFAULT '',
  		precondition VARCHAR(50) NOT NULL DEFAULT '',
  		PRIMARY KEY  (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE task(
			id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
			wid INT(11) NOT NULL DEFAULT 0,
			pid INT(11) NOT NULL DEFAULT 0,
			tid INT(11) NOT NULL DEFAULT 0,
			name VARCHAR(11) NOT NULL DEFAULT '',
  		description VARCHAR(100) NOT NULL DEFAULT '',
  		urlpattern VARCHAR(100) NOT NULL DEFAULT '',
  		urlgenerate VARCHAR(11) NOT NULL DEFAULT '',
  		PRIMARY KEY  (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;