CREATE TABLE workspace(
			id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
			wid VARCHAR(11) NOT NULL DEFAULT 0,
			name VARCHAR(11) NOT NULL DEFAULT '',
  		description VARCHAR(50) NOT NULL DEFAULT '',
  		PRIMARY KEY  (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE project(
			id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
			wid VARCHAR(11) NOT NULL DEFAULT 0,
			pid VARCHAR(11) NOT NULL DEFAULT 0,
			name VARCHAR(30) NOT NULL DEFAULT '',
  		description VARCHAR(100) NOT NULL DEFAULT '',
  		datasource VARCHAR(40) NOT NULL DEFAULT '',
  		schedule VARCHAR(30) NOT NULL DEFAULT '',
  		precondition VARCHAR(50) NOT NULL DEFAULT '',
  		PRIMARY KEY  (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE task(
			id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
			wid VARCHAR(11) NOT NULL DEFAULT 0,
			pid VARCHAR(11) NOT NULL DEFAULT 0,
			tid VARCHAR(11) NOT NULL DEFAULT 0,
			name VARCHAR(30) NOT NULL DEFAULT '',
  		description VARCHAR(100) NOT NULL DEFAULT '',
  		urlpattern VARCHAR(100) NOT NULL DEFAULT '',
  		urlgenerate VARCHAR(11) NOT NULL DEFAULT '',
  		isloop VARCHAR(11) NOT NULL DEFAULT '',
  		PRIMARY KEY  (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


create table data(
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    wid VARCHAR(11) NOT NULL DEFAULT '',
    pid VARCHAR(11) NOT NULL DEFAULT '',
    tid VARCHAR(11) NOT NULL DEFAULT '',
    dataid VARCHAR(11) NOT NULL DEFAULT '',
    description VARCHAR(255) NOT NULL DEFAULT '',
    property VARCHAR(255) NOT NULL DEFAULT '',
    rowKey  VARCHAR(100)  NOT NULL DEFAULT '',
    foreignKey  VARCHAR(100) NOT NULL DEFAULT '',
    foreignValue VARCHAR(100) NOT NULL DEFAULT '',
    link VARCHAR(100) NOT NULL DEFAULT '',
    processWay  VARCHAR(100) NOT NULL DEFAULT '',
    lcondition VARCHAR(10) NOT NULL DEFAULT '',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table regex(
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    wid VARCHAR(11) NOT NULL DEFAULT '',
    pid VARCHAR(11) NOT NULL DEFAULT '',
    tid VARCHAR(11) NOT NULL DEFAULT '',
    tagname VARCHAR(50) NOT NULL DEFAULT '',
    path VARCHAR(200) NOT NULL DEFAULT '',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;