<%@ page import="java.util.Map" %>
<%@ page import="java.util.HashMap" %>
<%@ page import="java.util.ArrayList" %>
<%
  Map<String,String> wmap = new HashMap<String,String>();
  Map<String,String> pmap = new HashMap<String,String>();
  Map<String,String> tmap = new HashMap<String,String>();
  Map<String,String> dmap = new HashMap<String,String>();
  Map<String,String> rmap = new HashMap<String,String>();
  Map<String,String> rmap1 = new HashMap<String,String>();
  Map<String,String> rmap2 = new HashMap<String,String>();
  Map<String,String> rmap3 = new HashMap<String,String>();
  Map<String,String> rmap4 = new HashMap<String,String>();
  ArrayList<Map<String,String>> list = new ArrayList<Map<String, String>>();
  wmap.put("wwid",request.getParameter("wwid"));
  wmap.put("wname",request.getParameter("wname"));
  wmap.put("wdescription",request.getParameter("wdescription"));
  pmap.put("pwid",request.getParameter("pwid"));
  pmap.put("ppid",request.getParameter("ppid"));
  pmap.put("pname",request.getParameter("pname"));
  pmap.put("pdescription",request.getParameter("pdescription"));
  pmap.put("pdatasource",request.getParameter("pdatasource"));
  pmap.put("pschedule",request.getParameter("pschedule"));
  pmap.put("pprecondition",request.getParameter("pprecondition"));
  tmap.put("twid",request.getParameter("twid"));
  tmap.put("tpid",request.getParameter("tpid"));
  tmap.put("ttid",request.getParameter("ttid"));
  tmap.put("tdescription",request.getParameter("tdescription"));
  tmap.put("turlpattern",request.getParameter("turlpattern"));
  tmap.put("turlgenerate",request.getParameter("turlgenerate"));
  tmap.put("tisloop",request.getParameter("tisloop"));
  dmap.put("dwid",request.getParameter("dwid"));
  dmap.put("dpid",request.getParameter("dpid"));
  dmap.put("dtid",request.getParameter("dtid"));
  dmap.put("ddataid",request.getParameter("ddataid"));
  dmap.put("ddescription",request.getParameter("ddescription"));
  dmap.put("dname1",request.getParameter("dname1"));
  dmap.put("dname2",request.getParameter("dname2"));
  dmap.put("dname3",request.getParameter("dname3"));
  dmap.put("dname4",request.getParameter("dname4"));
  dmap.put("dname5",request.getParameter("dname5"));
  dmap.put("dname6",request.getParameter("dname6"));
  dmap.put("dname7",request.getParameter("dname7"));
  dmap.put("dname8",request.getParameter("dname8"));
  dmap.put("dname9",request.getParameter("dname9"));
  dmap.put("dname10",request.getParameter("dname10"));
  dmap.put("drowkey",request.getParameter("drowkey"));
  dmap.put("dforeignkey",request.getParameter("dforeignkey"));
  dmap.put("dforeignvalue",request.getParameter("dforeignvalue"));
  dmap.put("dlink",request.getParameter("dlink"));
  dmap.put("dprocessway",request.getParameter("dprocessway"));

  rmap.put("rwid5",request.getParameter("rwid5"));
  rmap.put("rpid5",request.getParameter("rpid5"));
  rmap.put("rtid5",request.getParameter("rtid5"));
  rmap.put("rtagname5",request.getParameter("rtagname5"));
  rmap.put("rpath5",request.getParameter("rpath5"));
  rmap1.put("rwid1",request.getParameter("rwid1"));
  rmap1.put("rpid1",request.getParameter("rpid1"));
  rmap1.put("rtid1",request.getParameter("rtid1"));
  rmap1.put("rtagname1",request.getParameter("rtagname1"));
  rmap1.put("rpath1",request.getParameter("rpath1"));
  rmap2.put("rwid2",request.getParameter("rwid2"));
  rmap2.put("rpid2",request.getParameter("rpid2"));
  rmap2.put("rtid2",request.getParameter("rtid2"));
  rmap2.put("rtagname2",request.getParameter("rtagname2"));
  rmap2.put("rpath2",request.getParameter("rpath2"));
  rmap3.put("rwid3",request.getParameter("rwid3"));
  rmap3.put("rpid3",request.getParameter("rpid3"));
  rmap3.put("rtid3",request.getParameter("rtid3"));
  rmap3.put("rtagname3",request.getParameter("rtagname3"));
  rmap3.put("rpath3",request.getParameter("rpath3"));
  rmap4.put("rwid4",request.getParameter("rwid4"));
  rmap4.put("rpid4",request.getParameter("rpid4"));
  rmap4.put("rtid4",request.getParameter("rtid4"));
  rmap4.put("rtagname4",request.getParameter("rtagname4"));
  rmap4.put("rpath4",request.getParameter("rpath4"));
  list.add(rmap);
  list.add(rmap1);
  list.add(rmap2);
  list.add(rmap3);
  list.add(rmap4);
%>
